name: Template CI - Mocha Tests (Push/Manual/Scheduled)

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *" 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests (JUnit XML)
        run: npm test

      - name: Generate HTML report
        run: npm run test:report

      - name: Upload test reports - XML and HTML
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results/